package com.tcs.exceptions;


//An exception is an object
//An objects are created in runtime
public class TestException {
	public static void main(String[] args) {
		
		try {
			System.out.println(10/0);
		}
		catch(ArithmeticException e)
		{
			System.out.println(e.toString());
		}
		System.out.println("After Division");
	}

}
